In [2]:
import pandas as pd
import numpy as np
from googlemaps import Client as GoogleMaps

# step 1 - generate a distance matrix

I wanted to visualize the distance between each city (any kind of settelment) in israel to its nearesrt hospital.
to that end, I wanted to create a distance matrix table in whice the indexies are israel's cities and the column heads are 
hospitals. 
this would allow me to easly find the closest hospital to each city (minimum of each raw)

In the previus steps I've generated two tables, now storedin *.csv files:
1. lamas_2018_WGS.csv - A LAMAS report with all cities of israel - and WGS coords I've addded
2. hospitals.csv - All hospitals in israel and their WGS coords I've generated using GMAPS API

In [3]:
#Loading hospitals file. note that the 'code' column is an un-official code I assigned, but I will use it from here on to 
#identify each hospital
file = r'..\csv\hospitals.csv'
hospitals = pd.read_csv(file)
hospitals.head()

   code    hebName      engName        lat       long
0     0       שיבא        Shiba  32.046710  34.842852
1     1       רמבם       Rambam  32.832978  34.985706
2     2  אסף הרופא  Asaf Harofe  31.966053  34.839418
3     3    וולפסון      Wolfson  32.036031  34.762707
4     4        זיו          Ziv  32.954157  35.492657

In [4]:
#Loading the lamas file with all cities in israel and WGS coords
file2 = r'..\csv\lamas_2018_with_wgs.csv'
lamas = pd.read_csv(file2)

In [5]:
lamas.head()

,code,nameHeb,pronaunce,district,shire,naturalArea,monicipal,metro,religion,population,...,altitude,orgazinationRelated,plansComit,policeArea,year,nameEng,localCuncil,name,lat,long
0,967,אבו ג'ווייעד (שבט),ABU JUWEI'ID,6,62,623.0,NaN,NaN,3.0,NaN,...,2040057100,NaN,699,15003711,2018,Abu Juway'ad,NaN,Abu Juway'ad,_,_
1,472,אבו גוש,ABU GHOSH,1,11,111.0,99.0,444.0,2.0,7543.0,...,2105263481,598.0,152,10002475,2018,Abu Ghosh,NaN,Abu Ghosh,31.806293,35.109193
2,473,אבו סנאן,ABU SINAN,2,24,245.0,99.0,NaN,2.0,13915.0,...,2160776284,19.0,252,10004315,2018,Abu Sinan,NaN,Abu Sinan,32.95803,35.171969
3,935,אבו סריחאן (שבט),ABU SUREIHAN,6,62,623.0,NaN,NaN,3.0,NaN,...,1865057450,NaN,699,10001937,2018,Abu Surayhan,NaN,Abu Surayhan,_,_
4,958,אבו עבדון (שבט),ABU ABDUN,6,62,623.0,NaN,NaN,3.0,NaN,...,1850057900,NaN,699,10001937,2018,Abu 'Abdun,NaN,Abu 'Abdun,31.301397,34.841655

In [6]:
#in the next steps I created a distance matrix in which each index is a city code, and each column head is a hospital code
disMat = pd.DataFrame({'code': lamas['code'], 'name' : lamas['name']})
disMat.index= lamas['code']

dis_to_hospital = pd.DataFrame(np.zeros((len(disMat), len(hospitals))))
dis_to_hospital.columns = hospitals['code']
dis_to_hospital.index = disMat.index

disMat = pd.concat([disMat,dis_to_hospital], join ='outer', copy = False, axis = 1)
disMat.head()

,code,name,0,1,2,3,4,5,6,7,...,19,20,21,22,23,24,25,26,27,28
code,,,,,,,,,,,,,,,,,,,,,
967,967,Abu Juway'ad,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
472,472,Abu Ghosh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
473,473,Abu Sinan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
935,935,Abu Surayhan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
958,958,Abu 'Abdun,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# step 2 - calculate distance from each city to each hospital

So now that we have the empty distance matrix, we can iterate over all cities in the list. For each city, we will itterate over all hospitals, and fill the distance matrix using the GMAPS Distance API.

For that you need to generate a GMAPS Distance API Key from your google cloud. this process cost money per each query, but google gives you free trials. (you still need to a a billing method)
Again, just google "get GMAPS Distance API credentiale

In [9]:
hospitals_coords = hospitals[['code', 'lat', 'long']]

In [14]:
#The getDist function itterate over cities and hospitals WGS coords to get thier driving distance.
#Note that after each city the function backup the current distance matrix to a csv file after each city itteration
def getDist(israel, hospitals_coords, disMat):
    '''
    INPUT :
        israel - df of israel with lat/long, indexes by lamas codes
        hospital_coord df with hospitals codes lat/long  position
        disMat - a distance matrix with cities as raws index and hospitals codes as columns
            it should be filled with GMAPS distance from each city to each jospital
    OUTPUT - distance matrix (disMat)
    '''
    gmaps = GoogleMaps('Enter Your Key Here')
    i = 0
    n_of_cities = len(israel)
    
    #itterate cities and hospitals
    for city_code in israel.index:
        city_lat = israel.loc[city_code,:]['lat']
        city_long = israel.loc[city_code,:]['long']
        origins = (city_lat,city_long)
        
        for hospital_code in hospitals_coords.index:
            hospital_lat = hospitals_coords.loc[hospital_code,:]['lat']
            hospital_long = hospitals_coords.loc[hospital_code,:]['long']
            destination = (hospital_lat, hospital_long)
            try:
                result = gmaps.distance_matrix(origins, destination, mode='driving')["rows"][0]["elements"][0]["distance"]["value"]
                disMat.loc[city_code, hospital_code] = result
                
                     
            except:
                pass
        i+=1
        
        #After each city is over - BACKUP
        print(f'finished {i} of {n_of_cities} cities')
        path = r'\3 Israel Hospitals\backup\\'
        name = str(city_code) + '.csv'
        new_path = path+name
        disMat.to_csv(path+name)
        
    return (israel, hospitals_coords, disMat)

In [15]:
results = getDist(israel, hospitals_coords, disMat)

finished 1 of 1220 cities
finished 2 of 1220 cities
finished 3 of 1220 cities
finished 4 of 1220 cities
finished 5 of 1220 cities
finished 6 of 1220 cities
finished 7 of 1220 cities
finished 8 of 1220 cities
finished 9 of 1220 cities
finished 10 of 1220 cities
finished 11 of 1220 cities
finished 12 of 1220 cities
finished 13 of 1220 cities
finished 14 of 1220 cities
finished 15 of 1220 cities
finished 16 of 1220 cities
finished 17 of 1220 cities
finished 18 of 1220 cities
finished 19 of 1220 cities
finished 20 of 1220 cities
finished 21 of 1220 cities
finished 22 of 1220 cities
finished 23 of 1220 cities
finished 24 of 1220 cities
finished 25 of 1220 cities
finished 26 of 1220 cities
finished 27 of 1220 cities
finished 28 of 1220 cities
finished 29 of 1220 cities
finished 30 of 1220 cities
finished 31 of 1220 cities
finished 32 of 1220 cities
finished 33 of 1220 cities
finished 34 of 1220 cities
finished 35 of 1220 cities
finished 36 of 1220 cities
finished 37 of 1220 cities
finished 38 of 1220 cities
finished 39 of 1220 cities
finished 40 of 1220 cities
finished 41 of 1220 cities
finished 42 of 1220 cities
finished 43 of 1220 cities
finished 44 of 1220 cities
finished 45 of 1220 cities
finished 46 of 1220 cities
finished 47 of 1220 cities
finished 48 of 1220 cities
finished 49 of 1220 cities
finished 50 of 1220 cities
finished 51 of 1220 cities
finished 52 of 1220 cities
finished 53 of 1220 cities
finished 54 of 1220 cities
finished 55 of 1220 cities
finished 56 of 1220 cities
finished 57 of 1220 cities
finished 58 of 1220 cities
finished 59 of 1220 cities
finished 60 of 1220 cities
finished 61 of 1220 cities
finished 62 of 1220 cities
finished 63 of 1220 cities
finished 64 of 1220 cities
finished 65 of 1220 cities
finished 66 of 1220 cities
finished 67 of 1220 cities
finished 68 of 1220 cities
finished 69 of 1220 cities
finished 70 of 1220 cities
finished 71 of 1220 cities
finished 72 of 1220 cities
finished 73 of 1220 cities
finished 74 of 1220 cities
finished 75 of 1220 cities
finished 76 of 1220 cities
finished 77 of 1220 cities
finished 78 of 1220 cities
finished 79 of 1220 cities
finished 80 of 1220 cities
finished 81 of 1220 cities
finished 82 of 1220 cities
finished 83 of 1220 cities
finished 84 of 1220 cities
finished 85 of 1220 cities
finished 86 of 1220 cities
finished 87 of 1220 cities
finished 88 of 1220 cities
finished 89 of 1220 cities
finished 90 of 1220 cities
finished 91 of 1220 cities
finished 92 of 1220 cities
finished 93 of 1220 cities
finished 94 of 1220 cities
finished 95 of 1220 cities
finished 96 of 1220 cities
finished 97 of 1220 cities
finished 98 of 1220 cities
finished 99 of 1220 cities
finished 100 of 1220 cities
finished 101 of 1220 cities
finished 102 of 1220 cities
finished 103 of 1220 cities
finished 104 of 1220 cities
finished 105 of 1220 cities
finished 106 of 1220 cities
finished 107 of 1220 cities
finished 108 of 1220 cities
finished 109 of 1220 cities
finished 110 of 1220 cities
finished 111 of 1220 cities
finished 112 of 1220 cities
finished 113 of 1220 cities
finished 114 of 1220 cities
finished 115 of 1220 cities
finished 116 of 1220 cities
finished 117 of 1220 cities
finished 118 of 1220 cities
finished 119 of 1220 cities
finished 120 of 1220 cities
finished 121 of 1220 cities
finished 122 of 1220 cities
finished 123 of 1220 cities
finished 124 of 1220 cities
finished 125 of 1220 cities
finished 126 of 1220 cities
finished 127 of 1220 cities
finished 128 of 1220 cities
finished 129 of 1220 cities
finished 130 of 1220 cities
finished 131 of 1220 cities
finished 132 of 1220 cities
finished 133 of 1220 cities
finished 134 of 1220 cities
finished 135 of 1220 cities
finished 136 of 1220 cities
finished 137 of 1220 cities
finished 138 of 1220 cities
finished 139 of 1220 cities
finished 140 of 1220 cities
finished 141 of 1220 cities
finished 142 of 1220 cities
finished 143 of 1220 cities
finished 144 of 1220 cities
finished 145 of 1220 cities
finished 146 of 1220 cities
finished 147 of 1220 cities
finished 148 of 1220 cities
finished 149 of 1220 cities
finished 150 of 1220 cities
finished 151 of 1220 cities
finished 152 of 1220 cities
finished 153 of 1220 cities
finished 154 of 1220 cities
finished 155 of 1220 cities
finished 156 of 1220 cities
finished 157 of 1220 cities
finished 158 of 1220 cities
finished 159 of 1220 cities
finished 160 of 1220 cities
finished 161 of 1220 cities
finished 162 of 1220 cities
finished 163 of 1220 cities
finished 164 of 1220 cities
finished 165 of 1220 cities
finished 166 of 1220 cities
finished 167 of 1220 cities
finished 168 of 1220 cities
finished 169 of 1220 cities
finished 170 of 1220 cities
finished 171 of 1220 cities
finished 172 of 1220 cities
finished 173 of 1220 cities
finished 174 of 1220 cities
finished 175 of 1220 cities
finished 176 of 1220 cities
finished 177 of 1220 cities
finished 178 of 1220 cities
finished 179 of 1220 cities
finished 180 of 1220 cities
finished 181 of 1220 cities
finished 182 of 1220 cities
finished 183 of 1220 cities
finished 184 of 1220 cities
finished 185 of 1220 cities
finished 186 of 1220 cities
finished 187 of 1220 cities
finished 188 of 1220 cities
finished 189 of 1220 cities
finished 190 of 1220 cities
finished 191 of 1220 cities
finished 192 of 1220 cities
finished 193 of 1220 cities
finished 194 of 1220 cities
finished 195 of 1220 cities
finished 196 of 1220 cities
finished 197 of 1220 cities
finished 198 of 1220 cities
finished 199 of 1220 cities
finished 200 of 1220 cities
finished 201 of 1220 cities
finished 202 of 1220 cities
finished 203 of 1220 cities
finished 204 of 1220 cities
finished 205 of 1220 cities
finished 206 of 1220 cities
finished 207 of 1220 cities
finished 208 of 1220 cities
finished 209 of 1220 cities
finished 210 of 1220 cities
finished 211 of 1220 cities
finished 212 of 1220 cities
finished 213 of 1220 cities
finished 214 of 1220 cities
finished 215 of 1220 cities
finished 216 of 1220 cities
finished 217 of 1220 cities
finished 218 of 1220 cities
finished 219 of 1220 cities
finished 220 of 1220 cities
finished 221 of 1220 cities
finished 222 of 1220 cities
finished 223 of 1220 cities
finished 224 of 1220 cities
finished 225 of 1220 cities
finished 226 of 1220 cities
finished 227 of 1220 cities
finished 228 of 1220 cities
finished 229 of 1220 cities
finished 230 of 1220 cities
finished 231 of 1220 cities
finished 232 of 1220 cities
finished 233 of 1220 cities
finished 234 of 1220 cities
finished 235 of 1220 cities
finished 236 of 1220 cities
finished 237 of 1220 cities
finished 238 of 1220 cities
finished 239 of 1220 cities
finished 240 of 1220 cities
finished 241 of 1220 cities
finished 242 of 1220 cities
finished 243 of 1220 cities
finished 244 of 1220 cities
finished 245 of 1220 cities
finished 246 of 1220 cities
finished 247 of 1220 cities
finished 248 of 1220 cities
finished 249 of 1220 cities
finished 250 of 1220 cities
finished 251 of 1220 cities
finished 252 of 1220 cities
finished 253 of 1220 cities
finished 254 of 1220 cities
finished 255 of 1220 cities
finished 256 of 1220 cities
finished 257 of 1220 cities
finished 258 of 1220 cities
finished 259 of 1220 cities
finished 260 of 1220 cities
finished 261 of 1220 cities
finished 262 of 1220 cities
finished 263 of 1220 cities
finished 264 of 1220 cities
finished 265 of 1220 cities
finished 266 of 1220 cities
finished 267 of 1220 cities
finished 268 of 1220 cities
finished 269 of 1220 cities
finished 270 of 1220 cities
finished 271 of 1220 cities
finished 272 of 1220 cities
finished 273 of 1220 cities
finished 274 of 1220 cities
finished 275 of 1220 cities
finished 276 of 1220 cities
finished 277 of 1220 cities
finished 278 of 1220 cities
finished 279 of 1220 cities
finished 280 of 1220 cities
finished 281 of 1220 cities
finished 282 of 1220 cities
finished 283 of 1220 cities
finished 284 of 1220 cities
finished 285 of 1220 cities
finished 286 of 1220 cities
finished 287 of 1220 cities
finished 288 of 1220 cities
finished 289 of 1220 cities
finished 290 of 1220 cities
finished 291 of 1220 cities
finished 292 of 1220 cities
finished 293 of 1220 cities
finished 294 of 1220 cities
finished 295 of 1220 cities
finished 296 of 1220 cities
finished 297 of 1220 cities

finished 298 of 1220 cities
finished 299 of 1220 cities
finished 300 of 1220 cities
finished 301 of 1220 cities
finished 302 of 1220 cities
finished 303 of 1220 cities
finished 304 of 1220 cities
finished 305 of 1220 cities
finished 306 of 1220 cities
finished 307 of 1220 cities
finished 308 of 1220 cities
finished 309 of 1220 cities
finished 310 of 1220 cities
finished 311 of 1220 cities
finished 312 of 1220 cities
finished 313 of 1220 cities
finished 314 of 1220 cities
finished 315 of 1220 cities
finished 316 of 1220 cities
finished 317 of 1220 cities
finished 318 of 1220 cities
finished 319 of 1220 cities
finished 320 of 1220 cities
finished 321 of 1220 cities
finished 322 of 1220 cities
finished 323 of 1220 cities
finished 324 of 1220 cities
finished 325 of 1220 cities
finished 326 of 1220 cities
finished 327 of 1220 cities
finished 328 of 1220 cities
finished 329 of 1220 cities
finished 330 of 1220 cities
finished 331 of 1220 cities
finished 332 of 1220 cities
finished 333 of 1220 cities
finished 334 of 1220 cities
finished 335 of 1220 cities
finished 336 of 1220 cities
finished 337 of 1220 cities
finished 338 of 1220 cities
finished 339 of 1220 cities
finished 340 of 1220 cities
finished 341 of 1220 cities
finished 342 of 1220 cities
finished 343 of 1220 cities
finished 344 of 1220 cities
finished 345 of 1220 cities
finished 346 of 1220 cities
finished 347 of 1220 cities
finished 348 of 1220 cities
finished 349 of 1220 cities
finished 350 of 1220 cities
finished 351 of 1220 cities
finished 352 of 1220 cities
finished 353 of 1220 cities
finished 354 of 1220 cities
finished 355 of 1220 cities
finished 356 of 1220 cities
finished 357 of 1220 cities
finished 358 of 1220 cities
finished 359 of 1220 cities
finished 360 of 1220 cities
finished 361 of 1220 cities
finished 362 of 1220 cities
finished 363 of 1220 cities
finished 364 of 1220 cities
finished 365 of 1220 cities
finished 366 of 1220 cities
finished 367 of 1220 cities
finished 368 of 1220 cities
finished 369 of 1220 cities
finished 370 of 1220 cities
finished 371 of 1220 cities
finished 372 of 1220 cities
finished 373 of 1220 cities
finished 374 of 1220 cities
finished 375 of 1220 cities
finished 376 of 1220 cities
finished 377 of 1220 cities
finished 378 of 1220 cities
finished 379 of 1220 cities
finished 380 of 1220 cities
finished 381 of 1220 cities
finished 382 of 1220 cities
finished 383 of 1220 cities
finished 384 of 1220 cities
finished 385 of 1220 cities
finished 386 of 1220 cities
finished 387 of 1220 cities
finished 388 of 1220 cities
finished 389 of 1220 cities
finished 390 of 1220 cities
finished 391 of 1220 cities
finished 392 of 1220 cities
finished 393 of 1220 cities
finished 394 of 1220 cities
finished 395 of 1220 cities
finished 396 of 1220 cities
finished 397 of 1220 cities
finished 398 of 1220 cities
finished 399 of 1220 cities
finished 400 of 1220 cities
finished 401 of 1220 cities
finished 402 of 1220 cities
finished 403 of 1220 cities
finished 404 of 1220 cities
finished 405 of 1220 cities
finished 406 of 1220 cities
finished 407 of 1220 cities
finished 408 of 1220 cities
finished 409 of 1220 cities
finished 410 of 1220 cities
finished 411 of 1220 cities
finished 412 of 1220 cities
finished 413 of 1220 cities
finished 414 of 1220 cities
finished 415 of 1220 cities
finished 416 of 1220 cities
finished 417 of 1220 cities
finished 418 of 1220 cities
finished 419 of 1220 cities
finished 420 of 1220 cities
finished 421 of 1220 cities
finished 422 of 1220 cities
finished 423 of 1220 cities
finished 424 of 1220 cities
finished 425 of 1220 cities
finished 426 of 1220 cities
finished 427 of 1220 cities
finished 428 of 1220 cities
finished 429 of 1220 cities
finished 430 of 1220 cities
finished 431 of 1220 cities
finished 432 of 1220 cities
finished 433 of 1220 cities
finished 434 of 1220 cities
finished 435 of 1220 cities
finished 436 of 1220 cities
finished 437 of 1220 cities
finished 438 of 1220 cities
finished 439 of 1220 cities
finished 440 of 1220 cities
finished 441 of 1220 cities
finished 442 of 1220 cities
finished 443 of 1220 cities
finished 444 of 1220 cities
finished 445 of 1220 cities
finished 446 of 1220 cities
finished 447 of 1220 cities
finished 448 of 1220 cities
finished 449 of 1220 cities
finished 450 of 1220 cities
finished 451 of 1220 cities
finished 452 of 1220 cities
finished 453 of 1220 cities
finished 454 of 1220 cities
finished 455 of 1220 cities
finished 456 of 1220 cities
finished 457 of 1220 cities
finished 458 of 1220 cities
finished 459 of 1220 cities
finished 460 of 1220 cities
finished 461 of 1220 cities
finished 462 of 1220 cities
finished 463 of 1220 cities
finished 464 of 1220 cities
finished 465 of 1220 cities
finished 466 of 1220 cities
finished 467 of 1220 cities
finished 468 of 1220 cities
finished 469 of 1220 cities
finished 470 of 1220 cities
finished 471 of 1220 cities
finished 472 of 1220 cities
finished 473 of 1220 cities
finished 474 of 1220 cities
finished 475 of 1220 cities
finished 476 of 1220 cities
finished 477 of 1220 cities
finished 478 of 1220 cities
finished 479 of 1220 cities
finished 480 of 1220 cities
finished 481 of 1220 cities
finished 482 of 1220 cities
finished 483 of 1220 cities
finished 484 of 1220 cities
finished 485 of 1220 cities
finished 486 of 1220 cities
finished 487 of 1220 cities
finished 488 of 1220 cities
finished 489 of 1220 cities
finished 490 of 1220 cities
finished 491 of 1220 cities
finished 492 of 1220 cities
finished 493 of 1220 cities
finished 494 of 1220 cities
finished 495 of 1220 cities
finished 496 of 1220 cities
finished 497 of 1220 cities
finished 498 of 1220 cities
finished 499 of 1220 cities
finished 500 of 1220 cities
finished 501 of 1220 cities
finished 502 of 1220 cities
finished 503 of 1220 cities
finished 504 of 1220 cities
finished 505 of 1220 cities
finished 506 of 1220 cities
finished 507 of 1220 cities
finished 508 of 1220 cities
finished 509 of 1220 cities
finished 510 of 1220 cities
finished 511 of 1220 cities
finished 512 of 1220 cities
finished 513 of 1220 cities
finished 514 of 1220 cities
finished 515 of 1220 cities
finished 516 of 1220 cities
finished 517 of 1220 cities
finished 518 of 1220 cities
finished 519 of 1220 cities
finished 520 of 1220 cities
finished 521 of 1220 cities
finished 522 of 1220 cities
finished 523 of 1220 cities
finished 524 of 1220 cities
finished 525 of 1220 cities
finished 526 of 1220 cities
finished 527 of 1220 cities
finished 528 of 1220 cities
finished 529 of 1220 cities
finished 530 of 1220 cities
finished 531 of 1220 cities
finished 532 of 1220 cities
finished 533 of 1220 cities
finished 534 of 1220 cities
finished 535 of 1220 cities
finished 536 of 1220 cities
finished 537 of 1220 cities
finished 538 of 1220 cities
finished 539 of 1220 cities
finished 540 of 1220 cities
finished 541 of 1220 cities
finished 542 of 1220 cities
finished 543 of 1220 cities
finished 544 of 1220 cities
finished 545 of 1220 cities
finished 546 of 1220 cities
finished 547 of 1220 cities
finished 548 of 1220 cities
finished 549 of 1220 cities
finished 550 of 1220 cities
finished 551 of 1220 cities
finished 552 of 1220 cities
finished 553 of 1220 cities
finished 554 of 1220 cities
finished 555 of 1220 cities
finished 556 of 1220 cities
finished 557 of 1220 cities
finished 558 of 1220 cities
finished 559 of 1220 cities
finished 560 of 1220 cities
finished 561 of 1220 cities
finished 562 of 1220 cities
finished 563 of 1220 cities
finished 564 of 1220 cities
finished 565 of 1220 cities
finished 566 of 1220 cities
finished 567 of 1220 cities
finished 568 of 1220 cities
finished 569 of 1220 cities
finished 570 of 1220 cities
finished 571 of 1220 cities
finished 572 of 1220 cities
finished 573 of 1220 cities
finished 574 of 1220 cities
finished 575 of 1220 cities
finished 576 of 1220 cities
finished 577 of 1220 cities
finished 578 of 1220 cities
finished 579 of 1220 cities
finished 580 of 1220 cities
finished 581 of 1220 cities
finished 582 of 1220 cities
finished 583 of 1220 cities
finished 584 of 1220 cities
finished 585 of 1220 cities
finished 586 of 1220 cities
finished 587 of 1220 cities
finished 588 of 1220 cities
finished 589 of 1220 cities
finished 590 of 1220 cities

finished 591 of 1220 cities
finished 592 of 1220 cities
finished 593 of 1220 cities
finished 594 of 1220 cities
finished 595 of 1220 cities
finished 596 of 1220 cities
finished 597 of 1220 cities
finished 598 of 1220 cities
finished 599 of 1220 cities
finished 600 of 1220 cities
finished 601 of 1220 cities
finished 602 of 1220 cities
finished 603 of 1220 cities
finished 604 of 1220 cities
finished 605 of 1220 cities
finished 606 of 1220 cities
finished 607 of 1220 cities
finished 608 of 1220 cities
finished 609 of 1220 cities
finished 610 of 1220 cities
finished 611 of 1220 cities
finished 612 of 1220 cities
finished 613 of 1220 cities
finished 614 of 1220 cities
finished 615 of 1220 cities
finished 616 of 1220 cities
finished 617 of 1220 cities
finished 618 of 1220 cities
finished 619 of 1220 cities
finished 620 of 1220 cities
finished 621 of 1220 cities
finished 622 of 1220 cities
finished 623 of 1220 cities
finished 624 of 1220 cities
finished 625 of 1220 cities
finished 626 of 1220 cities
finished 627 of 1220 cities
finished 628 of 1220 cities
finished 629 of 1220 cities
finished 630 of 1220 cities
finished 631 of 1220 cities
finished 632 of 1220 cities
finished 633 of 1220 cities
finished 634 of 1220 cities
finished 635 of 1220 cities
finished 636 of 1220 cities
finished 637 of 1220 cities
finished 638 of 1220 cities
finished 639 of 1220 cities
finished 640 of 1220 cities
finished 641 of 1220 cities
finished 642 of 1220 cities
finished 643 of 1220 cities
finished 644 of 1220 cities
finished 645 of 1220 cities
finished 646 of 1220 cities
finished 647 of 1220 cities
finished 648 of 1220 cities
finished 649 of 1220 cities
finished 650 of 1220 cities
finished 651 of 1220 cities
finished 652 of 1220 cities
finished 653 of 1220 cities
finished 654 of 1220 cities
finished 655 of 1220 cities
finished 656 of 1220 cities
finished 657 of 1220 cities
finished 658 of 1220 cities
finished 659 of 1220 cities
finished 660 of 1220 cities
finished 661 of 1220 cities
finished 662 of 1220 cities
finished 663 of 1220 cities
finished 664 of 1220 cities
finished 665 of 1220 cities
finished 666 of 1220 cities
finished 667 of 1220 cities
finished 668 of 1220 cities
finished 669 of 1220 cities
finished 670 of 1220 cities
finished 671 of 1220 cities
finished 672 of 1220 cities
finished 673 of 1220 cities
finished 674 of 1220 cities
finished 675 of 1220 cities
finished 676 of 1220 cities
finished 677 of 1220 cities
finished 678 of 1220 cities
finished 679 of 1220 cities
finished 680 of 1220 cities
finished 681 of 1220 cities
finished 682 of 1220 cities
finished 683 of 1220 cities
finished 684 of 1220 cities
finished 685 of 1220 cities
finished 686 of 1220 cities
finished 687 of 1220 cities
finished 688 of 1220 cities
finished 689 of 1220 cities
finished 690 of 1220 cities
finished 691 of 1220 cities
finished 692 of 1220 cities
finished 693 of 1220 cities
finished 694 of 1220 cities
finished 695 of 1220 cities
finished 696 of 1220 cities
finished 697 of 1220 cities
finished 698 of 1220 cities
finished 699 of 1220 cities
finished 700 of 1220 cities
finished 701 of 1220 cities
finished 702 of 1220 cities
finished 703 of 1220 cities
finished 704 of 1220 cities
finished 705 of 1220 cities
finished 706 of 1220 cities
finished 707 of 1220 cities
finished 708 of 1220 cities
finished 709 of 1220 cities
finished 710 of 1220 cities
finished 711 of 1220 cities
finished 712 of 1220 cities
finished 713 of 1220 cities
finished 714 of 1220 cities
finished 715 of 1220 cities
finished 716 of 1220 cities
finished 717 of 1220 cities
finished 718 of 1220 cities
finished 719 of 1220 cities
finished 720 of 1220 cities
finished 721 of 1220 cities
finished 722 of 1220 cities
finished 723 of 1220 cities
finished 724 of 1220 cities
finished 725 of 1220 cities
finished 726 of 1220 cities
finished 727 of 1220 cities
finished 728 of 1220 cities
finished 729 of 1220 cities
finished 730 of 1220 cities
finished 731 of 1220 cities
finished 732 of 1220 cities
finished 733 of 1220 cities
finished 734 of 1220 cities
finished 735 of 1220 cities
finished 736 of 1220 cities
finished 737 of 1220 cities
finished 738 of 1220 cities
finished 739 of 1220 cities
finished 740 of 1220 cities
finished 741 of 1220 cities
finished 742 of 1220 cities
finished 743 of 1220 cities
finished 744 of 1220 cities
finished 745 of 1220 cities
finished 746 of 1220 cities
finished 747 of 1220 cities
finished 748 of 1220 cities
finished 749 of 1220 cities
finished 750 of 1220 cities
finished 751 of 1220 cities
finished 752 of 1220 cities
finished 753 of 1220 cities
finished 754 of 1220 cities
finished 755 of 1220 cities
finished 756 of 1220 cities
finished 757 of 1220 cities
finished 758 of 1220 cities
finished 759 of 1220 cities
finished 760 of 1220 cities
finished 761 of 1220 cities
finished 762 of 1220 cities
finished 763 of 1220 cities
finished 764 of 1220 cities
finished 765 of 1220 cities
finished 766 of 1220 cities
finished 767 of 1220 cities
finished 768 of 1220 cities
finished 769 of 1220 cities
finished 770 of 1220 cities
finished 771 of 1220 cities
finished 772 of 1220 cities
finished 773 of 1220 cities
finished 774 of 1220 cities
finished 775 of 1220 cities
finished 776 of 1220 cities
finished 777 of 1220 cities
finished 778 of 1220 cities
finished 779 of 1220 cities
finished 780 of 1220 cities
finished 781 of 1220 cities
finished 782 of 1220 cities
finished 783 of 1220 cities
finished 784 of 1220 cities
finished 785 of 1220 cities
finished 786 of 1220 cities
finished 787 of 1220 cities
finished 788 of 1220 cities
finished 789 of 1220 cities
finished 790 of 1220 cities
finished 791 of 1220 cities
finished 792 of 1220 cities
finished 793 of 1220 cities
finished 794 of 1220 cities
finished 795 of 1220 cities
finished 796 of 1220 cities
finished 797 of 1220 cities
finished 798 of 1220 cities
finished 799 of 1220 cities
finished 800 of 1220 cities
finished 801 of 1220 cities
finished 802 of 1220 cities
finished 803 of 1220 cities
finished 804 of 1220 cities
finished 805 of 1220 cities
finished 806 of 1220 cities
finished 807 of 1220 cities
finished 808 of 1220 cities
finished 809 of 1220 cities
finished 810 of 1220 cities
finished 811 of 1220 cities
finished 812 of 1220 cities
finished 813 of 1220 cities
finished 814 of 1220 cities
finished 815 of 1220 cities
finished 816 of 1220 cities
finished 817 of 1220 cities
finished 818 of 1220 cities
finished 819 of 1220 cities
finished 820 of 1220 cities
finished 821 of 1220 cities
finished 822 of 1220 cities
finished 823 of 1220 cities
finished 824 of 1220 cities
finished 825 of 1220 cities
finished 826 of 1220 cities
finished 827 of 1220 cities
finished 828 of 1220 cities
finished 829 of 1220 cities
finished 830 of 1220 cities
finished 831 of 1220 cities
finished 832 of 1220 cities
finished 833 of 1220 cities
finished 834 of 1220 cities
finished 835 of 1220 cities
finished 836 of 1220 cities
finished 837 of 1220 cities
finished 838 of 1220 cities
finished 839 of 1220 cities
finished 840 of 1220 cities
finished 841 of 1220 cities
finished 842 of 1220 cities
finished 843 of 1220 cities
finished 844 of 1220 cities
finished 845 of 1220 cities
finished 846 of 1220 cities
finished 847 of 1220 cities
finished 848 of 1220 cities
finished 849 of 1220 cities
finished 850 of 1220 cities
finished 851 of 1220 cities
finished 852 of 1220 cities
finished 853 of 1220 cities
finished 854 of 1220 cities
finished 855 of 1220 cities
finished 856 of 1220 cities
finished 857 of 1220 cities
finished 858 of 1220 cities
finished 859 of 1220 cities
finished 860 of 1220 cities
finished 861 of 1220 cities
finished 862 of 1220 cities
finished 863 of 1220 cities
finished 864 of 1220 cities
finished 865 of 1220 cities
finished 866 of 1220 cities
finished 867 of 1220 cities
finished 868 of 1220 cities
finished 869 of 1220 cities
finished 870 of 1220 cities
finished 871 of 1220 cities
finished 872 of 1220 cities
finished 873 of 1220 cities
finished 874 of 1220 cities
finished 875 of 1220 cities
finished 876 of 1220 cities
finished 877 of 1220 cities
finished 878 of 1220 cities
finished 879 of 1220 cities
finished 880 of 1220 cities
finished 881 of 1220 cities
finished 882 of 1220 cities
finished 883 of 1220 cities

finished 884 of 1220 cities
finished 885 of 1220 cities
finished 886 of 1220 cities
finished 887 of 1220 cities
finished 888 of 1220 cities
finished 889 of 1220 cities
finished 890 of 1220 cities
finished 891 of 1220 cities
finished 892 of 1220 cities
finished 893 of 1220 cities
finished 894 of 1220 cities
finished 895 of 1220 cities
finished 896 of 1220 cities
finished 897 of 1220 cities
finished 898 of 1220 cities
finished 899 of 1220 cities
finished 900 of 1220 cities
finished 901 of 1220 cities
finished 902 of 1220 cities
finished 903 of 1220 cities
finished 904 of 1220 cities
finished 905 of 1220 cities
finished 906 of 1220 cities
finished 907 of 1220 cities
finished 908 of 1220 cities
finished 909 of 1220 cities
finished 910 of 1220 cities
finished 911 of 1220 cities
finished 912 of 1220 cities
finished 913 of 1220 cities
finished 914 of 1220 cities
finished 915 of 1220 cities
finished 916 of 1220 cities
finished 917 of 1220 cities
finished 918 of 1220 cities
finished 919 of 1220 cities
finished 920 of 1220 cities
finished 921 of 1220 cities
finished 922 of 1220 cities
finished 923 of 1220 cities
finished 924 of 1220 cities
finished 925 of 1220 cities
finished 926 of 1220 cities
finished 927 of 1220 cities
finished 928 of 1220 cities
finished 929 of 1220 cities
finished 930 of 1220 cities
finished 931 of 1220 cities
finished 932 of 1220 cities
finished 933 of 1220 cities
finished 934 of 1220 cities
finished 935 of 1220 cities
finished 936 of 1220 cities
finished 937 of 1220 cities
finished 938 of 1220 cities
finished 939 of 1220 cities
finished 940 of 1220 cities
finished 941 of 1220 cities
finished 942 of 1220 cities
finished 943 of 1220 cities
finished 944 of 1220 cities
finished 945 of 1220 cities
finished 946 of 1220 cities
finished 947 of 1220 cities
finished 948 of 1220 cities
finished 949 of 1220 cities
finished 950 of 1220 cities
finished 951 of 1220 cities
finished 952 of 1220 cities
finished 953 of 1220 cities
finished 954 of 1220 cities
finished 955 of 1220 cities
finished 956 of 1220 cities
finished 957 of 1220 cities
finished 958 of 1220 cities
finished 959 of 1220 cities
finished 960 of 1220 cities
finished 961 of 1220 cities
finished 962 of 1220 cities
finished 963 of 1220 cities
finished 964 of 1220 cities
finished 965 of 1220 cities
finished 966 of 1220 cities
finished 967 of 1220 cities
finished 968 of 1220 cities
finished 969 of 1220 cities
finished 970 of 1220 cities
finished 971 of 1220 cities
finished 972 of 1220 cities
finished 973 of 1220 cities
finished 974 of 1220 cities
finished 975 of 1220 cities
finished 976 of 1220 cities
finished 977 of 1220 cities
finished 978 of 1220 cities
finished 979 of 1220 cities
finished 980 of 1220 cities
finished 981 of 1220 cities
finished 982 of 1220 cities
finished 983 of 1220 cities
finished 984 of 1220 cities
finished 985 of 1220 cities
finished 986 of 1220 cities
finished 987 of 1220 cities
finished 988 of 1220 cities
finished 989 of 1220 cities
finished 990 of 1220 cities
finished 991 of 1220 cities
finished 992 of 1220 cities
finished 993 of 1220 cities
finished 994 of 1220 cities
finished 995 of 1220 cities
finished 996 of 1220 cities
finished 997 of 1220 cities
finished 998 of 1220 cities
finished 999 of 1220 cities
finished 1000 of 1220 cities
finished 1001 of 1220 cities
finished 1002 of 1220 cities
finished 1003 of 1220 cities
finished 1004 of 1220 cities
finished 1005 of 1220 cities
finished 1006 of 1220 cities
finished 1007 of 1220 cities
finished 1008 of 1220 cities
finished 1009 of 1220 cities
finished 1010 of 1220 cities
finished 1011 of 1220 cities
finished 1012 of 1220 cities
finished 1013 of 1220 cities
finished 1014 of 1220 cities
finished 1015 of 1220 cities
finished 1016 of 1220 cities
finished 1017 of 1220 cities
finished 1018 of 1220 cities
finished 1019 of 1220 cities
finished 1020 of 1220 cities
finished 1021 of 1220 cities
finished 1022 of 1220 cities
finished 1023 of 1220 cities
finished 1024 of 1220 cities
finished 1025 of 1220 cities
finished 1026 of 1220 cities
finished 1027 of 1220 cities
finished 1028 of 1220 cities
finished 1029 of 1220 cities
finished 1030 of 1220 cities
finished 1031 of 1220 cities
finished 1032 of 1220 cities
finished 1033 of 1220 cities
finished 1034 of 1220 cities
finished 1035 of 1220 cities
finished 1036 of 1220 cities
finished 1037 of 1220 cities
finished 1038 of 1220 cities
finished 1039 of 1220 cities
finished 1040 of 1220 cities
finished 1041 of 1220 cities
finished 1042 of 1220 cities
finished 1043 of 1220 cities
finished 1044 of 1220 cities
finished 1045 of 1220 cities
finished 1046 of 1220 cities
finished 1047 of 1220 cities
finished 1048 of 1220 cities
finished 1049 of 1220 cities
finished 1050 of 1220 cities
finished 1051 of 1220 cities
finished 1052 of 1220 cities
finished 1053 of 1220 cities
finished 1054 of 1220 cities
finished 1055 of 1220 cities
finished 1056 of 1220 cities
finished 1057 of 1220 cities
finished 1058 of 1220 cities
finished 1059 of 1220 cities
finished 1060 of 1220 cities
finished 1061 of 1220 cities
finished 1062 of 1220 cities
finished 1063 of 1220 cities
finished 1064 of 1220 cities
finished 1065 of 1220 cities
finished 1066 of 1220 cities
finished 1067 of 1220 cities
finished 1068 of 1220 cities
finished 1069 of 1220 cities
finished 1070 of 1220 cities
finished 1071 of 1220 cities
finished 1072 of 1220 cities
finished 1073 of 1220 cities
finished 1074 of 1220 cities
finished 1075 of 1220 cities
finished 1076 of 1220 cities
finished 1077 of 1220 cities
finished 1078 of 1220 cities
finished 1079 of 1220 cities
finished 1080 of 1220 cities
finished 1081 of 1220 cities
finished 1082 of 1220 cities
finished 1083 of 1220 cities
finished 1084 of 1220 cities
finished 1085 of 1220 cities
finished 1086 of 1220 cities
finished 1087 of 1220 cities
finished 1088 of 1220 cities
finished 1089 of 1220 cities
finished 1090 of 1220 cities
finished 1091 of 1220 cities
finished 1092 of 1220 cities
finished 1093 of 1220 cities
finished 1094 of 1220 cities
finished 1095 of 1220 cities
finished 1096 of 1220 cities
finished 1097 of 1220 cities
finished 1098 of 1220 cities
finished 1099 of 1220 cities
finished 1100 of 1220 cities
finished 1101 of 1220 cities
finished 1102 of 1220 cities
finished 1103 of 1220 cities
finished 1104 of 1220 cities
finished 1105 of 1220 cities
finished 1106 of 1220 cities
finished 1107 of 1220 cities
finished 1108 of 1220 cities
finished 1109 of 1220 cities
finished 1110 of 1220 cities
finished 1111 of 1220 cities
finished 1112 of 1220 cities
finished 1113 of 1220 cities
finished 1114 of 1220 cities
finished 1115 of 1220 cities
finished 1116 of 1220 cities
finished 1117 of 1220 cities
finished 1118 of 1220 cities
finished 1119 of 1220 cities
finished 1120 of 1220 cities
finished 1121 of 1220 cities
finished 1122 of 1220 cities
finished 1123 of 1220 cities
finished 1124 of 1220 cities
finished 1125 of 1220 cities
finished 1126 of 1220 cities
finished 1127 of 1220 cities
finished 1128 of 1220 cities
finished 1129 of 1220 cities
finished 1130 of 1220 cities
finished 1131 of 1220 cities
finished 1132 of 1220 cities
finished 1133 of 1220 cities
finished 1134 of 1220 cities
finished 1135 of 1220 cities
finished 1136 of 1220 cities
finished 1137 of 1220 cities
finished 1138 of 1220 cities
finished 1139 of 1220 cities
finished 1140 of 1220 cities
finished 1141 of 1220 cities
finished 1142 of 1220 cities
finished 1143 of 1220 cities
finished 1144 of 1220 cities
finished 1145 of 1220 cities
finished 1146 of 1220 cities
finished 1147 of 1220 cities
finished 1148 of 1220 cities
finished 1149 of 1220 cities
finished 1150 of 1220 cities
finished 1151 of 1220 cities
finished 1152 of 1220 cities
finished 1153 of 1220 cities
finished 1154 of 1220 cities
finished 1155 of 1220 cities
finished 1156 of 1220 cities
finished 1157 of 1220 cities
finished 1158 of 1220 cities
finished 1159 of 1220 cities
finished 1160 of 1220 cities
finished 1161 of 1220 cities
finished 1162 of 1220 cities
finished 1163 of 1220 cities
finished 1164 of 1220 cities
finished 1165 of 1220 cities
finished 1166 of 1220 cities
finished 1167 of 1220 cities
finished 1168 of 1220 cities
finished 1169 of 1220 cities
finished 1170 of 1220 cities

finished 1171 of 1220 cities
finished 1172 of 1220 cities
finished 1173 of 1220 cities
finished 1174 of 1220 cities
finished 1175 of 1220 cities
finished 1176 of 1220 cities
finished 1177 of 1220 cities
finished 1178 of 1220 cities
finished 1179 of 1220 cities
finished 1180 of 1220 cities
finished 1181 of 1220 cities
finished 1182 of 1220 cities
finished 1183 of 1220 cities
finished 1184 of 1220 cities
finished 1185 of 1220 cities
finished 1186 of 1220 cities
finished 1187 of 1220 cities
finished 1188 of 1220 cities
finished 1189 of 1220 cities
finished 1190 of 1220 cities
finished 1191 of 1220 cities
finished 1192 of 1220 cities
finished 1193 of 1220 cities
finished 1194 of 1220 cities
finished 1195 of 1220 cities
finished 1196 of 1220 cities
finished 1197 of 1220 cities
finished 1198 of 1220 cities
finished 1199 of 1220 cities
finished 1200 of 1220 cities
finished 1201 of 1220 cities
finished 1202 of 1220 cities
finished 1203 of 1220 cities
finished 1204 of 1220 cities
finished 1205 of 1220 cities
finished 1206 of 1220 cities
finished 1207 of 1220 cities
finished 1208 of 1220 cities
finished 1209 of 1220 cities
finished 1210 of 1220 cities
finished 1211 of 1220 cities
finished 1212 of 1220 cities
finished 1213 of 1220 cities
finished 1214 of 1220 cities
finished 1215 of 1220 cities
finished 1216 of 1220 cities
finished 1217 of 1220 cities
finished 1218 of 1220 cities
finished 1219 of 1220 cities
finished 1220 of 1220 cities

In [23]:
# results[0].to_csv('israel.csv')
# results[1].to_csv('hospitals_codes')
results[2].to_csv(r'..\csv\isrHospitalDisMat.csv')